# Copyright (C) 2019-2020 kenzo<kenzok8@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=NonniCAT
LUCI_DEPENDS:=
PKG_VERSION:=2.1.0.5
PKG_RELEASE:=20220505

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature