#
# Copyright (C) 2020 Openwrt
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=luci-theme-we
LUCI_PKGARCH:=all
PKG_VERSION:=2.1.0.5
PKG_RELEASE:=20220520


include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
